export const ADD_USERS = 'ADD_USERS';
export const USERS_LOADING = 'USERS_LOADING';
export const USERS_FAILED = 'USERS_FAILED';

export const ADD_GROUPS = 'ADD_GROUPS';
export const GROUPS_LOADING = 'GROUPS_LOADING';
export const GROUPS_FAILED = 'GROUPS_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_LOADING = 'COMMENTS_LOADING';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';