export const ADD_USERS = 'ADD_USERS';
export const USERS_LOADING = 'USERS_LOADING';
export const USERS_FAILED = 'USERS_FAILED';

export const ADD_GROUPS = 'ADD_GROUPS';
export const GROUPS_LOADING = 'GROUPS_LOADING';
export const GROUPS_FAILED = 'GROUPS_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_LOADING = 'COMMENTS_LOADING';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const ADD_NOTICES = 'ADD_NOTICES';
export const NOTICES_LOADING = 'NOTICES_LOADING';
export const NOTICES_FAILED = 'NOTICES_FAILED';

export const ADD_GROUPCHAT = 'ADD_GROUPCHAT';
export const GROUPCHAT_LOADING = 'GROUPCHAT_LOADING';
export const GROUPCHAT_FAILED = 'GROUPCHAT_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';